---
title: "Co-authors"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Co-authors

```{r echo=FALSE, message=FALSE, error=FALSE, warning=FALSE}
# library(easyPubMed)
library(tidyverse)
library(igraph)
library(visNetwork)
# load('vis_g.Rda')
author_df<-readRDS("author_df.Rds")
```

The nodes in the network represent researchers with whom we have published. Zoom in and navigate through the network!

```{r}
author_df<-author_df[author_df$co_authors%in%author_df$author,]%>%
  mutate(co_authors = ifelse(co_authors =="Torres Espin A", "Torres-Espin A", co_authors),
         author = ifelse(author =="Torres Espin A", "Torres-Espin A", author))%>%
  mutate(co_edge=paste(co_authors, author, sep = '_'))%>%
  group_by(co_edge)%>%
  summarise(count=n())%>%
  separate(co_edge, c('co_authors','author'),sep = '_')

# co_author<-data.frame(name = unique(author_df$co_authors))

author_df<-author_df%>%
  group_by(co_authors, author)%>%
  summarise(count = sum(count))
```

```{r}
author_g<-graph_from_data_frame(author_df,directed = F)
E(author_g)$weight<-author_df$count
author_g<-simplify(author_g)
V(author_g)$group<-rep("co-author", length(V(author_g)))
V(author_g)$group[377]<-"Abel"
# layout_nicely(author_g)
# plot(author_g)
```

```{r, fig.height=8, fig.width=8}
visIgraph(author_g)%>%
      visIgraphLayout(layout = "layout_with_fr")%>%
      visGroups()%>%
      visEdges(width = "weight")%>%
      visOptions(highlightNearest = list(enabled = T, hover = T), 
                 nodesIdSelection = T, selectedBy = "group",
                 height = "800px", width="100%")

```

Created in R using [easyPubMed](https://cran.r-project.org/web/packages/easyPubMed/index.html), [tidyverse](https://www.tidyverse.org/), [igraph](https://igraph.org/redirect.html) and [visNetwork](https://datastorm-open.github.io/visNetwork/)


[Learn how to make yours!](/post/network-coauthors/network.html)
