---
title: "Tools"
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Software
### syndRomics
#### An R package for reproducible analysis of disease space via principal components

The package implements functions for helping in the process of disease patterns analysis by means of principal components. These include component visualization, interpretation and stability analysis. The goal of the analysis is to understand complex disease states or patterns as common factors (syndromes) that can be quantified from measured variables through the use of computational and analytic approaches (Ferguson et al., 2011, Torres-Espin et al., 2020). In particular, principal component analysis (PCA) and related multivariate statistics has been used as primary toolkit for extracting disease patterns. For details on the analysis

[GitHub](https://github.com/ucsf-ferguson-lab/syndRomics)

**Citation**: Abel Torres-Espin, Austin Chou, J. Russell Huie, Nikos Kyritsis, Pavan Upadhyayula, and Adam R. Ferguson. Reproducible analysis of disease space via principal components using the novel R package syndRomics. https://doi.org/10.7554/eLife.61812

<div class = "badge open">Open Source</div>


### Neurite-J
#### An ImageJ plug-in for axonal growth analysis in organotypic cultures

Neurite-J is an ImageJ plug-in that works as an adaption of the Sholl method providing a semi-automatic tool for neurite outgrowth quantification in organotypic cultures. Neurite-J gives a good description of neurite growth providing counts of neurite number and neurite area at different distances from the organotypic explant. Neurite-J was developed in the Neuroplasticity and Repair Group of the University Autonomous of Barcenlona (UAB) by Dr. Abel Torres Espin.

[Download](https://imagejdocu.tudor.lu/plugin/analysis/neurite-j/start)

**Citation**: Torres-Espín A, Santos D, González-Pérez F, del Valle J, Navarro X. Neurite-J: An Image-J plug-in for axonal analisys in organotypic cultures. J Neurosci Meth 236:26–39

<div class = "badge open">Open Source</div>

### pOrg
#### An R package for data science project organization (In development)

The pOrg is a very lightweight R package for data science project organization in the speficied directory. It is intended to use at the starting of a new project to quickly generate a prefered project structure.

[GitHub](https://github.com/ATEspin/pOrg)

**Citation**: Abel Torres-Espin (2021) pOrg R package. https://github.com/ATEspin/pOrg

<div class = "badge open">Open Source</div>

### Animal Behaviour App

#### A set of Python apps to facilitate the analysis of animal behaviour

These are a set of Python-based GUI applications for the analysis of various rat behavioral tests performed for rehabilitation after spinal cord injury.

The programs were written by Abel Torres Espín for analysis at The Fouad Lab at the University of Alberta in Edmonton, Alberta.

**Applications:**

* `Xmaze`: analysis of X maze recordings for location and time spend in the different arms
* `Openfield`: analysis of Open field recordings for location and activity
* `Whitebox`: analysis of white box recordings for time spend in each box
* `SPGAnalysis`: analysis of single pellet reaching recordings for several metrics

[GitHub](https://github.com/ATEspin/Animal-Behaviour-apps)

<div class = "badge open">Open Source</div>


# Hardware
### Pellet Dispenser
#### A motorized pellet dispenser to deliver high intensity training of the single pellet reaching and grasping task in rats

The single pellet reaching and grasping (SPG) task is widely used to study forelimb motor performance in rodents and to provide rehabilitation after neurological disorders. Nonetheless, the time necessary to train animals precludes its use in settings where high-intensity training is required. In the current study, we developed a novel high-intensity training protocol for the SPG task based on a motorized pellet dispenser and a dual-window enclosure. We tested the protocol in naive adult rats and found 1) an increase in the intensity of training without increasing the task time and without affecting the overall performance of the animals, 2) a reduction in the variability within and between experiments in comparison to manual SPG training, and 3) a reduction in the time required to conduct experiments. In summary, we developed and tested a novel protocol for SPG training that provides higher-intensity training while reducing the variability of results observed with other protocols.

[Download Manual and 3D files](https://www.researchgate.net/publication/319356788_A_motorized_pellet_dispenser_to_deliver_high_intensity_training_of_the_single_pellet_task_in_rats)

**Citation**: Torres-Espín A, Forero J, Schmidt EKA, Fouad K, Fenrich KK. A motorized pellet dispenser to deliver high intensity training of the single pellet reaching and grasping task in rats. Behav Brain Res. 2018 Jan 15;336:67-76. doi: 10.1016/j.bbr.2017.08.033. Epub 2017 Aug 25. PMID: 28847445.

<div class = "badge open">Open Source</div>